<?php

require('../session.php');

require('fpdf.php');

class PDF extends FPDF
{
// Load data
function LoadData($file)
{
    // Read file lines
    $lines = file($file);
    $data = array();
    foreach($lines as $line)
        $data[] = explode(';',trim($line));
    return $data;
}



// Colored table
function FancyTable($header, $data)
{
    // Colors, line width and bold font
    $this->SetFillColor(0);
    $this->SetTextColor(255);
    $this->SetDrawColor(0,0,0);
    $this->SetLineWidth(.1);
    $this->SetFont('','B');
    // Header
    $w = array(28, 30, 30, 25,25,35);
    for($i=0;$i<count($header);$i++)
        $this->Cell($w[$i],7,$header[$i],1,0,'C',true);
    $this->Ln();
    // Color and font restoration
    $this->SetFillColor(224,235,255);
    $this->SetTextColor(0);
    $this->SetFont('');
    // Data
    $fill = false;
    foreach($data as $row)
    {
        $this->Cell($w[0],6,$row[0],'LR',0,'L',$fill);
        $this->Cell($w[1],6,$row[1],'LR',0,'L',$fill);
        $this->Cell($w[2],6,$row[2],'LR',0,'L',$fill);
        $this->Cell($w[3],6,$row[3],'LR',0,'L',$fill);
        $this->Cell($w[4],6,$row[4],'LR',0,'L',$fill);
        $this->Cell($w[5],6,$row[5],'LR',0,'L',$fill);
        // $this->Cell($w[2],6,number_format($row[2]),'LR',0,'R',$fill);
        // $this->Cell($w[3],6,number_format($row[3]),'LR',0,'R',$fill);
        $this->Ln();
        $fill = !$fill;
    }
    // Closing line
    $this->Cell(array_sum($w),0,'','T');
}

function Header()
{
    // Select Arial bold 15
    $this->SetFont('Arial','B',15);
    // Move to the right
    $this->Cell(80);
    // Framed title
    $this->Cell(30,10,'Customer Application Report',0,0,'C');
    // Line break
    $this->Ln(20);
}

function Footer()
{
    $user = "Generated by ". $_SESSION["username"];
    // Go to 1.5 cm from bottom
    $this->SetY(-15);
    // Select Arial italic 8
    $this->SetFont('Arial','I',8);
    // Print centered page number
    $this->Cell(0,10,'ABC Bank '.date('l jS \of F Y H:i'). ', ' . $user . ' - Page '.$this->PageNo(),0,0,'C');
}

}


$db = new SQLite3('C:\xampp\server\sqlite\dbw-assignment-db\abcbank.db');

$sql = "
    SELECT 
    c.app_id as `App ID`, 
    c.first_name as `First Name`, 
    c.last_name as `Last Name`, 
    a.status as Status, 
    substr(p.placement,2) || 'GBP' as `Placement Amount`, 
    a.date_created as `Date Created`, 
    a.last_modified as `Last Modified`
    from customers c
    left join applications a on a.app_id = c.app_id
    left join products p on p.id = a.selected_product
    order by a.date_created asc";

$stmt = $db->query($sql);

while($row=$stmt->fetchArray(SQLITE3_NUM)){

    $res [] = $row;

}



$pdf = new PDF();


// Column headings
$header = array(
        'App ID',
        'First Name',
        'Last Name',
        'Status',
        'Placement Amount',
        'Date Created'        
    );

    

        // 'Last Updated'

// Data loading
// $data = $pdf->LoadData('countries.txt');

$title = 'Customer Application Report';


$pdf->SetFont('Arial','',8);
$pdf->SetTextColor(0);
$pdf->AddPage();
$pdf->Image('../../assets/img/logo-abc.png',10,10,-300);
$pdf->SetTitle($title);
$pdf->FancyTable($header,$res);
$pdf->Output();
?>